default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: alone_development

test:
  <<: *default
  database: alone_test


production:
  <<: *default
  database: alone_production
  username: alone
  password: <%= ENV['ALONE_DATABASE_PASSWORD'] %>
